name: disposebag_example
description: disposebag_example
publish_to: none
version: 1.5.1

environment:
  sdk: '<4.0.0'

dependencies:
  disposebag: any

dependency_overrides:
  disposebag:
    path: ../../disposebag