language: dart
dart:
  - stable
  - dev
script:
  - dartanalyzer --fatal-infos --fatal-warnings ./lib ./test
  - dartfmt -n ./lib --set-exit-if-changed
  - pub get
  - pub global activate coverage
  - pub run test test/disposebag_test.dart --coverage --coverage-path=lcov.info
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
