language: dart
dart:
  - stable
  - dev
script:
  - dartanalyzer --fatal-infos --fatal-warnings ./lib ./test
  - dartfmt -n ./lib --set-exit-if-changed
  - pub get
  - pub global activate coverage
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates --wait-paused &
  - dart test/disposebag_test.dart
  - pub global run coverage:format_coverage --package-root=packages --report-on lib --in coverage.json --out lcov.info --lcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
