language: dart
dart:
  - stable
  - dev
script:
  - pub run test
  - pub global activate coverage
  - dart --observe=8111 test/disposebag_test.dart &
  - sleep 1
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --package-root=packages --report-on lib --in coverage.json --out lcov.info --lcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
