name: disposebag
description: A package helps to cancel StreamSubscriptions and close Sinks.
version: 1.5.1
homepage: https://github.com/hoc081098/disposebag.git
repository: https://github.com/hoc081098/disposebag.git
issue_tracker: https://github.com/hoc081098/disposebag/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
#  mockito: ^3.0.0