name: disposebag
description: A package to help disposing Streams and closing Sinks easily.
version: 1.0.0+1
homepage: https://github.com/hoc081098/disposebag.git
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: '>=1.1.1 <2.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0