name: disposebag
description: A package to help disposing Streams and closing Sinks easily.
version: 1.5.0-nullsafety.0
homepage: https://github.com/hoc081098/disposebag.git
repository: https://github.com/hoc081098/disposebag.git
issue_tracker: https://github.com/hoc081098/disposebag/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  collection: ^1.15.0-nullsafety.5

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
#  mockito: ^3.0.0