name: disposebag
description: A package to help disposing Streams and closing Sinks easily.
version: 1.5.0-nullsafety.1
homepage: https://github.com/hoc081098/disposebag.git
repository: https://github.com/hoc081098/disposebag.git
issue_tracker: https://github.com/hoc081098/disposebag/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.2
#  mockito: ^3.0.0