name: disposebag
description: A package to help disposing Streams and closing Sinks easily.
version: 1.4.0
homepage: https://github.com/hoc081098/disposebag.git
repository: https://github.com/hoc081098/disposebag.git
issue_tracker: https://github.com/hoc081098/disposebag/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  collection: ^1.14.11

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
  mockito: ^3.0.0