name: disposebag
description: A package to help disposing Streams and closing Sinks.
version: 0.0.9
homepage: https://github.com/hoc081098/disposebag.git
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  rxdart:
  pedantic: ^1.0.0
  test: ^1.0.0
