name: disposebag
description: A package to help disposing Streams and closing Sinks easily.
version: 1.2.0-nullsafety
homepage: https://github.com/hoc081098/disposebag.git
repository: https://github.com/hoc081098/disposebag.git
issue_tracker: https://github.com/hoc081098/disposebag/issues

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.10.0'

dependencies:
  meta: '>=1.3.0-nullsafety <1.3.0'
  collection: '>=1.15.0-nullsafety <1.15.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
#  mockito: ^3.0.0

dependency_overrides:
  pedantic:
    git: git://github.com/dart-lang/pedantic.git
  test:
    git:
      url: git://github.com/dart-lang/test.git
      path: pkgs/test