name: Run example

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch:

jobs:
  run-example:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.4
        with:
          sdk: stable

      - name: Print Dart version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Run lib/disposebag_example.dart
        run: dart run lib/disposebag_example.dart